### ISSUE TITLE
npm install fluid-draw

### ISSUE THREAD

**Issue by iftikhaar** [paul-nechifor/fluid-draw#1]
rm lib/*; coffee --compile --bare --output lib src

**Comment by iftikhaar** [comment]
There is an issue with this command while installing fluid Draw through npm.
![capswsture](https://cloud.githubusercontent.com/assets/26734261/24393124/4ee0ae84-13b0-11e7-9a51-c2ba1b75136d.JPG)

**Comment by paul-nechifor** [comment]
Sorry for the horribly late reply! When I wrote this I was heavily into CoffeeScript and instead of publishing the JavaScript code this package publishes the CoffeeScript code.

I've changed the package to include the JavaScript code. Note that this requires a C++ package. I've also added instructions in the readme about how to get it.
